services:
  reminder_service:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    container_name: reminder_service
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/reminder_service.log:/app/reminder_service.log
    networks:
      - reminder_net

networks:
  reminder_net:
    driver: bridge
